"""
Reconstructed API stub for the frozen module `ledMatrix` (from ledMatrix.py).

SOURCE: MiniHexa firmware minihexa_20250929_0x000.bin (MicroPython v1.21.0).
        Low-level driver for the segment/dot-matrix display used by
        DEV_Digitaltube. Names EXACT from qstr pool; bodies not recovered.

Recovered constants: WRITE_DATA_MODE_Z, WRITE_DATA_MODE_G, DISPLAY_EN,
DISPLAY_DIS, _SEGMENTS, _LIGHT. Recovered font tables: _number_5x8,
Character_font_6x8, reversed_font, and glyphs _speechless, _smile.
"""

class LedMatrix:  # exact class name not in local pool
    __pin: object
    def _start(self) -> None: ...
    def _stop(self) -> None: ...
    def _send(self, byte: int) -> None: ...
    def _send_cmd(self, cmd: int) -> None: ...
    def _send_dat(self, addr: int, data: int) -> None: ...
    def showNum(self, num) -> None: ...
    def setBrightness(self, light: int) -> None: ...
    def setLedOnOff(self, onoff) -> None: ...
    def drawBitMap(self, data_list) -> None: ...
    def drawStr(self, row: int, column: int, s: str) -> None: ...
